.TH PIPHTML 1 2024-Dec "" "Render Html from the rscript data"
.SH NAME
pipHtml \- pipHtml(rscript)
.SH SYNOPSIS
\fIpipHtml(rscript)\fR
.SH OPTIONS
.PP
\fBrscript\fB \fR\- . the rscript object data or the filepath of a rscript notebook document or the text contents of the rscript notebook.
.PP
.SH VALUE
.PP
the generated html document content string.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pipHtml at notebook.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
