.\" man page create by R# package system.
.TH ENGINE 1 2000-1月 "listen" "listen"
.SH NAME
listen \- listen on the tcp port for run the lsp http service
.SH SYNOPSIS
\fIlisten(\fBport\fR as integer = 321, 
\fBvscode_clr\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
listen on the tcp port for run the lsp http service
.PP
.SH OPTIONS
.PP
\fBport\fB \fR\- -. 
.PP
.SH SEE ALSO
engine
.SH FILES
.PP
languageserver.dll
.PP
