.\" man page create by R# package system.
.TH ENGINE 1 2000-1月 "toHtml" "toHtml"
.SH NAME
toHtml \- 
.SH SYNOPSIS
\fItoHtml(\fBnb\fR as <generic> Notebook, 
\fBstyle\fR as string = \fB<NULL>\fR, 
\fBstrict\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBnb\fB \fR\- -. 
.PP
.PP
\fBstyle\fB \fR\- 
 the css style text
. 
.PP
.SH SEE ALSO
engine
.SH FILES
.PP
languageserver.dll
.PP
